<?php
session_start();
?>
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Login | Online Grocery Store</title>
  <meta name="description" content="Login to your Online Grocery Store account. Secure access with CAPTCHA verification.">
  <meta name="keywords" content="login, online grocery, secure">
  <link rel="canonical" href="https://www.teach.scam.keele.ac.uk/prin/x5z36/Web_Development_21011707/login.php">
  <script src="https://cdn.tailwindcss.com"></script>
</head>
<body class="bg-gray-100 min-h-screen flex flex-col">
  <header class="bg-green-700">
    <div class="container mx-auto px-4 py-4 text-white text-center">
      <h1 class="text-3xl font-bold">Login</h1>
    </div>
  </header>
  
  <!--Login Form -->
  <main class="container mx-auto px-4 py-8 flex-grow">
    <div class="bg-white p-8 rounded shadow-md max-w-md mx-auto">
      <form action="login_action.php" method="post">
        <div class="mb-4">
          <label class="block text-gray-700 mb-2">Email:</label>
          <input type="email" name="email" required class="w-full border border-gray-300 p-2 rounded focus:outline-none focus:ring-2 focus:ring-green-500" />
        </div>
        <div class="mb-4">
          <label class="block text-gray-700 mb-2">Password:</label>
          <input type="password" name="password" required class="w-full border border-gray-300 p-2 rounded focus:outline-none focus:ring-2 focus:ring-green-500" />
        </div>
        <div class="mb-4">
          <label class="block text-gray-700 mb-2">Captcha (type exactly what you see):</label>
          <input type="text" name="captcha" required class="w-full border border-gray-300 p-2 rounded focus:outline-none focus:ring-2 focus:ring-green-500" />
          <!-- Display CAPTCHA image generated by captcha.php -->
          <img src="captcha.php" alt="CAPTCHA Image" class="mt-2">
        </div>
        <button type="submit" class="w-full bg-green-700 text-white p-2 rounded hover:bg-green-800 transition duration-300">Login</button>
      </form>
    </div>
  </main>
  
  <!-- Footer -->
  <footer class="bg-green-700">
    <div class="container mx-auto px-4 py-4 text-center text-white">
      &copy; <?php echo date("Y"); ?> Online Grocery Store.
    </div>
  </footer>
</body>
</html>
